# Generated by Django 5.2.1 on 2025-05-13 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_room_reservation_delete_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
