# Generated by Django 5.2.1 on 2025-05-20 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_room_is_featured'),
        ('base', '0005_reservation_email_reservation_full_name_and_more'),
    ]

    operations = [
    ]
