# Generated by Django 5.2.1 on 2025-05-18 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_reservation_payment_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='image',
        ),
        migrations.AddField(
            model_name='room',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='room_images/', verbose_name='Image 1'),
        ),
        migrations.AddField(
            model_name='room',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='room_images/', verbose_name='Image 2'),
        ),
        migrations.AddField(
            model_name='room',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='room_images/', verbose_name='Image 3'),
        ),
        migrations.AddField(
            model_name='room',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='room_images/', verbose_name='Image 4'),
        ),
    ]
